In [72]:
import pandas as pd
score = pd.DataFrame({
    '姓名':['张三','李四','王五','赵六','钱七'],
    '数学':[85,92,78,88,95],
    '英语':[90,88,85,92,80],
    '物理':[75,80,88,85,90]
})
score['总分'] = score[['数学','英语','物理']].sum(axis=1)
score['平均分'] = score[['数学','英语','物理']].mean(axis=1)
score.sort_values(['总分'],ascending=False).head(3)
score[ (score['数学']>90)|(score['英语']>85) ]
score

   姓名  数学  英语  物理   总分        平均分
0  张三  85  90  75  250  83.333333
1  李四  92  88  80  260  86.666667
2  王五  78  85  88  251  83.666667
3  赵六  88  92  85  265  88.333333
4  钱七  95  80  90  265  88.333333

In [92]:
# 第二题
data = pd.DataFrame({
    '产品信息':['A','B','C','D'],
    '单价':[100,150,200,120],
    '销量':[50,30,20,40]
})
data['总销售额'] = data['单价'] * data['销量']
# 计算最大销售额
data.nlargest(1,columns=['总销售额'])
data.sort_values('总销售额',ascending=False)
data

  产品信息   单价  销量  总销售额
0    A  100  50  5000
1    B  150  30  4500
2    C  200  20  4000
3    D  120  40  4800